#!/usr/bin/env python3
"""
Generates a reproducible bank of 1000 Minesweeper ("Demineur") levels.

Design choices (so future solver baselines can rely on them):
- Every level is fully deterministic: given the same `seed`, the same
  mine layout is produced by the algorithm below (Python's Mersenne
  Twister, random.Random(seed).sample on the cell list in row-major
  order). This means a Python solver can regenerate the exact same
  board from levels.json without needing the JS engine.
- Classic rule: the very first cell a player reveals can never be a
  mine, and (to avoid "guess immediately" starts) none of its up-to-8
  neighbors are mines either. That safe zone is centered on the grid
  and is stored explicitly as `start_cell` so every implementation
  (JS game, Python solver) opens the same way.
- Levels are split across the three classic difficulties plus a
  "mixed" bucket with randomized dimensions/density, so baselines can
  be evaluated both on standard boards and on generalization.
"""
import json
import random

DIFFICULTIES = [
    # (name, width, height, mines, count)
    ("beginner", 9, 9, 10, 300),
    ("intermediate", 16, 16, 40, 300),
    ("expert", 30, 16, 99, 200),
    ("mixed", None, None, None, 200),  # randomized per-level
]

MIXED_SIZE_RANGE = (8, 24)      # width/height in [8,24]
MIXED_DENSITY_RANGE = (0.12, 0.22)  # mine density fraction


def safe_zone(width, height, cx, cy):
    """Cells that must never be mines: the start cell + its neighbors."""
    cells = set()
    for dy in (-1, 0, 1):
        for dx in (-1, 0, 1):
            x, y = cx + dx, cy + dy
            if 0 <= x < width and 0 <= y < height:
                cells.add((x, y))
    return cells


def make_level(level_id, difficulty, width, height, mines, seed):
    rng = random.Random(seed)
    cx, cy = width // 2, height // 2
    forbidden = safe_zone(width, height, cx, cy)

    all_cells = [(x, y) for y in range(height) for x in range(width)]
    candidates = [c for c in all_cells if c not in forbidden]

    if mines > len(candidates):
        raise ValueError(
            f"Level {level_id}: too many mines ({mines}) for board "
            f"{width}x{height} minus safe zone ({len(candidates)} free cells)"
        )

    mine_cells = rng.sample(candidates, mines)
    mine_cells.sort(key=lambda c: (c[1], c[0]))  # deterministic ordering

    return {
        "id": level_id,
        "difficulty": difficulty,
        "width": width,
        "height": height,
        "mines": mines,
        "seed": seed,
        "start_cell": [cx, cy],
        "mine_cells": [[x, y] for x, y in mine_cells],
    }


def main():
    levels = []
    level_id = 1
    master_rng = random.Random(20260818)  # date-stamped master seed

    for name, w, h, m, count in DIFFICULTIES:
        for _ in range(count):
            seed = master_rng.randrange(1, 2**31 - 1)
            if name == "mixed":
                w_i = master_rng.randint(*MIXED_SIZE_RANGE)
                h_i = master_rng.randint(*MIXED_SIZE_RANGE)
                density = master_rng.uniform(*MIXED_DENSITY_RANGE)
                m_i = max(1, int(w_i * h_i * density))
                # keep mines comfortably below max possible given safe zone
                max_mines = w_i * h_i - 9
                m_i = min(m_i, max_mines)
            else:
                w_i, h_i, m_i = w, h, m

            levels.append(make_level(level_id, name, w_i, h_i, m_i, seed))
            level_id += 1

    assert len(levels) == 1000, len(levels)

    with open("levels.json", "w") as f:
        json.dump(levels, f, separators=(",", ":"))

    # Also emit as a plain JS global so the webpage can <script src="levels.js">
    # it directly and play offline without hitting file:// CORS restrictions.
    with open("levels.js", "w") as f:
        f.write("// Auto-generated by generate_levels.py — do not edit by hand.\n")
        f.write("const LEVEL_BANK = ")
        json.dump(levels, f, separators=(",", ":"))
        f.write(";\n")

    print(f"Generated {len(levels)} levels.")
    by_diff = {}
    for lv in levels:
        by_diff[lv["difficulty"]] = by_diff.get(lv["difficulty"], 0) + 1
    print("By difficulty:", by_diff)


if __name__ == "__main__":
    main()